export const ErrorCode = {
    ERROR_INIT: -1,
    ERROR_SUCCESS: 0,
    ERROR_COMMON: 1,
    UN_AUTHORIZE: 401,
    NO_CONNECTION: 404,
    INVALID_ACCOUNT: 103,
    LOGIN_FAIL_USERNAME_PASSWORD_MISMATCH: 102,
};